apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-helm
spec:
  replicas: 1
  selector: 
    matchLabels:
        service: postgre-helm
  template:
    metadata:
      labels:
        service: postgre-helm
    spec:
      containers:
        - name: postgre-helm
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db0
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres-data"
      volumes:
        - hostPath:
            path: "/postgre-vol"
          name: postgres-data